# Generated by Django 4.1.6 on 2023-02-06 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rideservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'open'), ('confirmed', 'confirmed'), ('completed', 'completed')], default='open', max_length=20)),
                ('is_Share', models.BooleanField(blank=True, default=False)),
                ('destination', models.CharField(max_length=100)),
                ('arrival_time', models.DateTimeField(null=True)),
                ('capacity', models.IntegerField(default=0)),
                ('vehicle_type', models.CharField(blank=True, max_length=50)),
                ('special_request', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RideUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=68)),
                ('is_driver', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='xxx', max_length=50)),
                ('license_num', models.CharField(default='xxx', max_length=100)),
                ('capacity', models.IntegerField(default=4)),
                ('otherInfo', models.CharField(blank=True, max_length=200, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rideservice.rideuser')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='rideservice.rideuser'),
        ),
        migrations.AddField(
            model_name='ride',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='rideservice.rideuser'),
        ),
        migrations.AddField(
            model_name='ride',
            name='sharer',
            field=models.ManyToManyField(blank=True, related_name='sharer', to='rideservice.rideuser'),
        ),
    ]
